web survey/chart/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('home.urls', 'home'), namespace='home')),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

web survey/home/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name="index"),
    path('login', views.loged, name="login"),
    path('csv', views.csv, name="csv"),
    path('survey', views.survey, name="survey"),
    path('master', views.master, name="master"),
    path('alljson', views.alljson, name="alljson"),
    path('jsonchart/<int:id>', views.jsonchart),
    path('edit/<int:id>', views.editmaster),
    path('start/<int:id>', views.start),
    path('delete/<str:act>/<int:id>', views.delete),
    path('editjson/<int:id>', views.editjson),
    path('json/<int:id>', views.json),
    path('detail/<int:id>', views.masterdetail),
    

]

web survey/templates/user/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>{{ title }}</title>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/d3/3.4.11/d3.min.js"></script>
<script src="https://cdn.rawgit.com/jasondavies/d3-cloud/v1.2.1/build/d3.layout.cloud.js"></script>

<script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.3/dist/Chart.min.js"></script>
    <style>
      #word-cloud{
    height: 100vh;
    width: 100vw;
    margin: 0 auto;
    }

    body, html{
        margin: 0;
        padding: 0;
    }
    </style>
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx"
      crossorigin="anonymous"
    />
    <link rel="stylesheet" href="{% static 'css/home.css' %}" />
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.2/css/all.min.css"
      integrity="sha512-1sCRPdkRXhBV2PBLUdRb4tMg1w2YPf37qatUFeS7zlBy7jJI8Lf4VHwWfZZfpXtYSLy85pkm9GaYVYMfw5BC1A=="
      crossorigin="anonymous"
      referrerpolicy="no-referrer"
    />
    <link
      rel="stylesheet"
      type="text/css"
      href="https://cdn.datatables.net/1.12.1/css/jquery.dataTables.css"
    />
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.2/css/all.min.css"
      integrity="sha512-1sCRPdkRXhBV2PBLUdRb4tMg1w2YPf37qatUFeS7zlBy7jJI8Lf4VHwWfZZfpXtYSLy85pkm9GaYVYMfw5BC1A=="
      crossorigin="anonymous"
      referrerpolicy="no-referrer"
    />
  </head>
  <body>
    <nav class="navbar navbar-expand-lg bg-light">
        <div class="container px-5">
          <a class="navbar-brand" href="#">{{brand}}</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ms-auto mb-4 mb-lg-0 me-4">
              {% if user.is_authenticated %}
              <a class="nav-link me-3 {% if active == 1 %} active text-primary {% endif %}"  href="{% url 'home:index' %}"><span class="text-dark">Welcome </span> {{user.username}}</a>
              <li class="nav-item">
              </li>
              {% endif %}
              <li class="nav-item">
                <a class="nav-link {% if active == 1 %} active text-primary {% endif %}"  href="{% url 'home:index' %}">HOME</a>
              </li>
              <li class="nav-item">
                <a class="nav-link {% if active == 2 %} active text-primary {% endif %}" href="{% url 'home:csv' %}">CSV</a>
              </li>
              <li class="nav-item">
                <a class="nav-link {% if active == 3 %} active text-primary {% endif %}" href="{% url 'home:survey' %}">SURVEY</a>
              </li>
              {% if user.is_authenticated %}
              <a class="nav-link me-3"  href="{% url 'home:master' %}"><span class="text-dark">MASTER</a>
              <li class="nav-item">
              </li>
              {% endif %}
            </ul>
            <a href="admin/" class="btn btn-outline-primary mx-1">Super admin</a>
            {% if user.is_authenticated %}
            <a href="{% url 'home:login' %}?logout=logout" class="btn btn-danger">Logout</a>
            {% else %}
            <button class="btn btn-outline-success mx-1" type="button" data-bs-toggle="modal" data-bs-target="#login">Login</button>
            {% endif %}
          </div>
        </div>
      </nav>
      
      {% block content %}
      {% endblock content %}

      <div class="modal fade" id="login" tabindex="-1" aria-labelledby="loginModalLabel" aria-hidden="true">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="loginModalLabel">Modal title</h5>
              <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <form action="{% url 'home:login' %}" method="POST" >
              {% csrf_token %}
              <input type="hidden" name="log" value="login">
              <div class="modal-body">
                <div class="mb-3">
                  <label for="username" class="form-label">Username</label>
                  <input type="text" class="form-control" name="username" id="username" >
                </div>
                <div class="mb-3">
                  <label for="password" class="form-label">Password</label>
                  <input type="password" class="form-control" name="password" id="password">
                </div>
              </div>
              <div class="container">
                <a href="{% url 'home:login' %}">tidak punya akun ? buat disini</a>
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <input type="submit" value="Login" class="btn btn-primary">
              </form>
            </div>
          </div>
        </div>
      </div>
    <script src="{% static 'js/home.js' %}"></script>
    <script src="{% static 'js/d3-index.js' %}"></script>
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa"
      crossorigin="anonymous"
    ></script>
    <script
      type="text/javascript"
      charset="utf8"
      src="https://cdn.datatables.net/1.12.1/js/jquery.dataTables.js"
    ></script>
    <script>
      $(document).ready(function () {
        $("#table_csv").DataTable({
        });
      });
    </script>
  </body>
</html>

web survey/templates/user/chart.html
{% extends 'user/base.html' %}

{% block content %}

  <div id="container" style="width: 75%;">
    <canvas id="population-chart" data-url="{% url 'jsnochart' %}"></canvas>
  </div>

  <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.3/dist/Chart.min.js"></script>
  <script>

    $(function () {

      var $populationChart = $("#population-chart");
      $.ajax({
        url: $populationChart.data("url"),
        success: function (data) {

          var ctx = $populationChart[0].getContext("2d");

          new Chart(ctx, {
            type: 'bar',
            data: {
              labels: data.labels,
              datasets: [{
                label: 'Population',
                backgroundColor: 'blue',
                data: data.data
              }]          
            },
            options: {
              responsive: true,
              legend: {
                position: 'top',
              },
              title: {
                display: true,
                text: 'Population Bar Chart'
              }
            }
          });

        }
      });

    });

  </script>

{% endblock %}

web survey/templates/user/csv.html
{% extends 'user/base.html' %}

{% block content %}
<div class="row justify-content-center pt-5">
  <div class="col-md-3">
    <form action="" method="post" enctype="multipart/form-data">
      {% csrf_token %}
      <div class="d-flex justify-content-center">
        <div class="drop-zone pt-5">
          <span class="drop-zone__prompt">Klik atau Drop file CSV disini</span>
          <input type="file" name="csv" class="drop-zone__input" />
        </div>
      </div>
      <div class="d-grid gap-2 px-3 mt-3">
        <button type="submit" class="btn btn-primary"><i class="fas fa-save me-2"></i>Simpan</button>
      </div>
    </form>
    
  </div>
  <div class="col-md-7">
    <table id="table_csv" class="display">
      <thead>
        <tr class="text-center">
          <th>Nama</th>
          <th>tanggal</th>
          <th>parse</th>
          <th>action</th>
        </tr>
      </thead>
      <tbody>
        {% for s in csvvalue %}
        <tr class="text-center">
          <td>{{s.nama}}</td>
          <td>{{s.tanggal}}</td>
          <td>
            {% if s.parse %}
            parsed
            {% else %}
            <a href="?parse=ya&id={{s.id}}" class="btn btn-warning me-2"><i class="fas fa-refresh"></i>parse</a>
            {% endif %}
          </td>
          <td>
            <a href="?parse=gak&id={{s.id}}" class="btn btn-warning me-2"><i class="fas fa-eye"></i>Lihat</a>
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
  </div>

  <div class="d-flex justify-content-center">
    <div id="cloud"></div>
  </div>
  {% for y in value %}
    <div style="display: none;">
      <div class="valueName">{{y.name}}</div>
      <div class="valueSize">{{y.size}}</div>
    </div>
  {% endfor %}
  <div class="row justify-content-center">
    <div class="col-10">
      <canvas id="all-chart" data-url="../jsonchart/{{get}}"></canvas>
    </div>
  </div>
  
  <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.3/dist/Chart.min.js"></script>
  <script>
  
    $(function () {
  
      var $populationChart = $("#all-chart");
      $.ajax({
        url: $populationChart.data("url"),
        success: function (data) {
  
          var ctx = $populationChart[0].getContext("2d");
  
          new Chart(ctx, {
            type: 'bar',
            data: {
              labels: data.labels,
              datasets: [{
                label: 'Survey chart',
                backgroundColor: 'blue',
                data: data.data
              }]          
            },
            options: {
              responsive: true,
              legend: {
                position: 'top',
              },
              title: {
                display: true,
                text: 'Survey'
              }
            }
          });
  
        }
      });
  
    });
  
  </script>
{% endblock content %}

web survey/templates/user/index.html
{% extends 'user/base.html' %}

{% block content %}
<div class="container pt-5">
  <h1 class="display-4">Selamat datang di survey {{PDSI}}</h1>
  <p class="lead">Ini adalah website django yang dibuat untuk memenuhi mata kuliah</p>
  <hr class="my-4">
  <p>website ini kedepannya akan dipakai untuk keperluan penting mendatang</p>
  <p class="lead">
    <a class="btn btn-primary btn-lg" href="{% url 'home:survey' %}" role="button">Mulai survey</a>
  </p>
</div>
{% endblock content %}

web survey/templates/user/login.html
{% extends 'user/base.html' %}

{% block content %}
<div class="row justify-content-center mt-5 pt-5">
    <div class="col-md-5">
        <form method="POST">
            {% csrf_token %}
            <input type="hidden" name="log" value="regist">
            <div class="mb-3">
              <label for="username" class="form-label">username</label>
              <input type="text" class="form-control" id="username" name="username">
              <div id="emailHelp" class="form-text">We'll never share your email with anyone else.</div>
            </div>

            <div class="mb-3">
                <label for="email" class="form-label">email</label>
                <input type="email" class="form-control" id="email" name="email">
              </div>
            <div class="mb-3">
            <select class="form-select" name="age">
                <option selected>Umur</option>
                {% for i in '012345678901234567890'|make_list %}
                    <option value="{{ forloop.counter |add:18}}">{{ forloop.counter |add:18}}</option>
                {% endfor %}
              </select>
            </div>
            <select class="form-select" name="sex">
                <option selected>Jenis kelamin</option>
                <option value="1">Laki - Laki</option>
                <option value="2">Perempuan</option>
              </select>
            <div class="mb-3">
              <label for="password" class="form-label">Password</label>
              <input type="password" class="form-control" id="password" name="password">
            </div>
            <button type="submit" class="btn btn-primary">Daftar</button>
          </form>
    </div>
</div>
{% endblock content %}

web survey/templates/user/start.html
{% extends 'user/base.html' %}

{% block content %}
<div class="text-center display-6 mt-5 mb-3">
    {{survey.name}}
</div>
<div class="row justify-content-start">
    <div class="col-md-2"></div>
    <div class="col-md-8">
        <form action="" method="post">
            {% csrf_token %}
            {% for q in question %}
            {% if q.text %}
            <div class="mb-3">
                <label for="text{{q.id}}" class="form-label"><h5> {{ forloop.counter }}. {{q.name}}</h5></label>
                <textarea class="form-control" name="text{{q.id}}" id="text{{q.id}}" rows="3"></textarea>
            </div>
            {% else %}
            <h5> {{ forloop.counter }}. {{q.name}}</h5>
            <div class="d-flex ms-5 mb-5">
                {% for a in q.answer %}
                <div class="form-check me-3">
                    <input class="form-check-input" type="radio" required name="answer{{q.id}}" id="{{q.id}}{{a.id}}" value="{{a.id}}">
                    <label class="form-check-label" for="{{q.id}}{{a.id}}">
                        {{a.name}}
                    </label>
                </div>
                {% endfor %}
            </div>
            {% endif %}
            <hr>
            {% endfor %}
            <div class="d-grid gap-2">
                <input type="submit" value="Kirim" class="btn btn-success">
              </div>
        </form>
    </div>
</div>
{% endblock content %}

web survey/templates/user/survey.html
{% extends 'user/base.html' %}

{% block content %}
<div class="text-center display-4">{{title}}</div>
{% if not login %}<div class="text-center h4 text-danger">login untuk memulai survey</div>{% endif %}
<div class="container">
  <div class="row justify-content-center">
    {% for s in survey %}
    <div class="col-md-4 text-center">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">{{s.name}}</h5>
          <div class="btn btn-outline-primary disabled"><i class="fas fa-question me-2"></i>{{s.pertanyaan}}</div>
          <div class="btn btn-outline-primary disabled"><i class="fas fa-user me-2"></i>{{s.responde}}</div>
          <hr>
          {% if s.finish %}
          <a href="start/{{s.id}}" class="btn btn-primary"><i class="fas fa-pencil me-2"></i>edit jawaban</a>
          {% else %}
          <a href="start/{{s.id}}" class="btn btn-primary {% if not login %} disabled {% endif %}">Mulai survey</a>
          {% endif %}
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
</div>
{% endblock content %}